// Generated by Selenium IDE
var assert = require("assert"),
webdriver = require("selenium-webdriver"),
conf_file = process.argv[3] || "conf/single.conf.js";
const By = webdriver.By;
var caps = require("../" + conf_file).capabilities;
var buildDriver = function(caps) {
  return new webdriver.Builder()
    .usingServer(
      "http://" +
      "mgrass" +
      ":" +
      "tKUuMLH0V4SCP8FpdrJBXGPrTMludNcN7xuHmR80CVtI6Gj7kt" +
      "@hub.lambdatest.com/wd/hub"
    )
    .withCapabilities(caps)
    .build();
};

describe('Idelaure', function() {
  var driver;
  this.timeout(0);

  beforeEach(function(done) {
    caps.name = this.currentTest.title;
    driver = buildDriver(caps);
    done();
  });

  afterEach(function(done) {
    if (this.currentTest.isPassed()) {
      driver.executeScript("lambda-status=passed");
    } else {
      driver.executeScript("lambda-status=failed");
    }
    driver.quit().then(function() {
      done();
    });
  });
  
  it('Idelaure', async function() {
    await driver.get("https://www.idelaure.fr/")
    // await driver.manage().window().setRect({ width: 1486, height: 903 })
    await driver.findElement(By.css(".post-9377 > .button")).click()
    await driver.findElement(By.css(".post-9377 .attachment-woocommerce_thumbnail")).click()
    await driver.findElement(By.name("add-to-cart")).click()
    await driver.findElement(By.css(".wc-forward")).click()
    await driver.findElement(By.css(".site-title > a")).click()
    await driver.findElement(By.css(".cartcontents")).click()
    await driver.findElement(By.css(".checkout-button")).click()
    await driver.findElement(By.id("billing_last_name")).click()
    await driver.findElement(By.id("billing_last_name")).sendKeys("qsdqs")
    await driver.findElement(By.id("billing_first_name")).click()
    await driver.findElement(By.id("billing_first_name")).sendKeys("dqsdqd")
  })
})
